- name: Clone Git repository, check if Apache is installed (master)
  hosts: master
  tasks:
    - name: Include variables from main.yaml
      include_vars: vars/main.yaml

    - name: Clone Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"

    - name: Ensure Apache is installed on master node
      package:
        name: "{{ apache_package_name[ansible_os_family] }}"
        state: present
      tags: apache

    - name: Ensure apache website directory exists
      file:
        path: "{{ website_doc_root }}"
        state: directory

    - name: Copy website files from tmp to desired website location
      command: cp -r "{{ repo_dest }}" "{{ website_doc_root }}"

- name: Copy website files to slave nodes (if applicable)
  hosts: slaves
  tasks:
    - name: Include variables from main.yaml
      include_vars: vars/main.yaml

    - name: Ensure the appropriate Apache package is installed on slave nodes
      package:
        name: "{{ apache_package_name[ansible_os_family] }}"
        state: present
      tags: apache

    - name: Ensure apache website directory exists
      file:
        path: "{{ website_doc_root }}"
        state: directory

    - name: Copy website files from master to slave nodes
      synchronize:
        src: "{{ repo_dest }}"
        dest: "{{ website_doc_root }}"


- name: Start Apache service on all nodes (if installed)
  hosts: all
  tasks:
    - name: Include variables from main.yaml
      include_vars: vars/main.yaml

    - name: Start Apache service (if present)
      service:
        name: "{{ apache_service_name }}"
        state: started
      tags: apache
